# Generated by Django 5.0.6 on 2024-06-02 07:45

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusCode', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('notional', models.DecimalField(decimal_places=6, max_digits=19)),
                ('termCode', models.CharField(choices=[('Weekly', 'Weekly')], default='Weekly', max_length=10)),
                ('startDate', models.DateField()),
                ('frequency', models.IntegerField()),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.db.models.functions.datetime.Now())),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('loanSysId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
    ]
