# Generated by Django 5.0.6 on 2024-06-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='statusCode',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='termCode',
            new_name='term',
        ),
    ]
