# Generated by Django 5.0.6 on 2024-06-02 19:18

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.db.models.functions.datetime.Now())),
                ('amount', models.DecimalField(decimal_places=6, max_digits=19)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.payment')),
            ],
        ),
    ]
