# Generated by Django 5.0.6 on 2024-06-03 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_created_alter_repayment_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='createdBy',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='loanSysId',
            new_name='loan',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentDate',
            new_name='payment_date',
        ),
    ]
